[font]
size = 7

[font.normal]
#family = "PxPlus IBM VGA8"
family = "TempleOS"




# Windows 95 Color Scheme
# To have the authentic experience in Chicago95 GTK Theme.

# Default colors
[colors.primary]
foreground = '#000000'
background = '#FFFFFF'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#A80000'
green   = '#00A800'
yellow  = '#A85400'
blue    = '#0000A8'
magenta = '#A800A8'
cyan    = '#00A8A8'
white   = '#A8A8A8'

# Bright colors
[colors.bright]
black   = '#545454'
red     = '#FC5454'
green   = '#54FC54'
yellow  = '#FCFC54'
blue    = '#5454FC'
magenta = '#FC54FC'
cyan    = '#54FCFC'
white   = '#FFFFFF'